# Generated by Django 3.2.21 on 2023-09-17 20:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='first_icon',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='film',
            name='second_icon',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='icon'),
        ),
    ]
