# Generated by Django 3.2.21 on 2023-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20230917_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticcomment',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='criticcomment',
            name='critic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membercomment',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
