# Generated by Django 3.2.21 on 2023-10-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20231011_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='film',
            new_name='movie',
        ),
    ]
