# Generated by Django 3.2.21 on 2023-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_rename_film_score_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticcomment',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='membercomment',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
